
spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Chongqing&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  application:
    name: USER

  redis:
    host: 192.168.214.128
    password: 123456
    timeout: 5000       #最大超时时间
    lettuce:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8     #连接池中的最大空闲连接 默认 0
        min-idle: 0     #连接池中的最小空闲连接 默认 0

server:
  port: 8080
